// Code generated by go generate; DO NOT EDIT.

package lexer

type TokenType int

const (
	TokenEOF TokenType = iota
	TokenIdentifier
	TokenDot
	TokenEquals
	TokenValue
	TokenTraefik
	TokenHTTP
	TokenTCP
	TokenUDP
	TokenRouters
	TokenServices
	TokenServersTransports
	TokenServersTransport
	TokenLoadBalancer
	TokenServer
	TokenHealthCheck
	TokenHeaders
	TokenSticky
	TokenCookie
	TokenResponseForwarding
	TokenForwardingTimeouts
	TokenProxyProtocol
	TokenTLS
	TokenDomains
	TokenEnable
	TokenName
	TokenRule
	TokenService
	TokenEntryPoints
	TokenEntryPoint
	TokenMiddlewares
	TokenPriority
	TokenCertResolver
	TokenOptions
	TokenPassthrough
	TokenURL
	TokenScheme
	TokenPort
	TokenIP
	TokenAddress
	TokenInsecureSkipVerify
	TokenPassHostHeader
	TokenPath
	TokenInterval
	TokenTimeout
	TokenMethod
	TokenHostname
	TokenFollowRedirects
	TokenSecure
	TokenHTTPOnly
	TokenSameSite
	TokenFlushInterval
	TokenVersion
	TokenTerminationDelay
	TokenServerName
	TokenRootCAs
	TokenMaxIdleConnsPerHost
	TokenDisableHTTP2
	TokenPeerCertURI
	TokenDialTimeout
	TokenResponseHeaderTimeout
	TokenIdleConnTimeout
	TokenReadIdleTimeout
	TokenPingTimeout
	TokenMain
	TokenSANs
)

var StringToTokenType = map[string]TokenType{
	"traefik":               TokenTraefik,
	"http":                  TokenHTTP,
	"tcp":                   TokenTCP,
	"udp":                   TokenUDP,
	"routers":               TokenRouters,
	"services":              TokenServices,
	"serverstransports":     TokenServersTransports,
	"serverstransport":      TokenServersTransport,
	"loadbalancer":          TokenLoadBalancer,
	"server":                TokenServer,
	"healthcheck":           TokenHealthCheck,
	"headers":               TokenHeaders,
	"sticky":                TokenSticky,
	"cookie":                TokenCookie,
	"responseforwarding":    TokenResponseForwarding,
	"forwardingtimeouts":    TokenForwardingTimeouts,
	"proxyprotocol":         TokenProxyProtocol,
	"tls":                   TokenTLS,
	"domains":               TokenDomains,
	"enable":                TokenEnable,
	"name":                  TokenName,
	"rule":                  TokenRule,
	"service":               TokenService,
	"entrypoints":           TokenEntryPoints,
	"entrypoint":            TokenEntryPoint,
	"middlewares":           TokenMiddlewares,
	"priority":              TokenPriority,
	"certresolver":          TokenCertResolver,
	"options":               TokenOptions,
	"passthrough":           TokenPassthrough,
	"url":                   TokenURL,
	"scheme":                TokenScheme,
	"port":                  TokenPort,
	"ip":                    TokenIP,
	"address":               TokenAddress,
	"insecureskipverify":    TokenInsecureSkipVerify,
	"passhostheader":        TokenPassHostHeader,
	"path":                  TokenPath,
	"interval":              TokenInterval,
	"timeout":               TokenTimeout,
	"method":                TokenMethod,
	"hostname":              TokenHostname,
	"followredirects":       TokenFollowRedirects,
	"secure":                TokenSecure,
	"httponly":              TokenHTTPOnly,
	"samesite":              TokenSameSite,
	"flushinterval":         TokenFlushInterval,
	"version":               TokenVersion,
	"terminationdelay":      TokenTerminationDelay,
	"servername":            TokenServerName,
	"rootcas":               TokenRootCAs,
	"maxidleconnsperhost":   TokenMaxIdleConnsPerHost,
	"disablehttp2":          TokenDisableHTTP2,
	"peercerturi":           TokenPeerCertURI,
	"dialtimeout":           TokenDialTimeout,
	"responseheadertimeout": TokenResponseHeaderTimeout,
	"idleconntimeout":       TokenIdleConnTimeout,
	"readidletimeout":       TokenReadIdleTimeout,
	"pingtimeout":           TokenPingTimeout,
	"main":                  TokenMain,
	"sans":                  TokenSANs,
}
