package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
)

type tokenDefinition struct {
	Name   string
	Lexeme string
}

func main() {
	input := flag.String("in", "", "token definition file")
	output := flag.String("out", "", "generated Go file")
	flag.Parse()

	if *input == "" || *output == "" {
		fmt.Fprintln(os.Stderr, "usage: tokengen -in tokens.def -out tokens_gen.go")
		os.Exit(2)
	}

	definitions, err := readDefinitions(*input)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	source, err := generate(definitions)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := os.WriteFile(*output, source, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func readDefinitions(path string) ([]tokenDefinition, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	defer file.Close()

	definitions := make([]tokenDefinition, 0)
	scanner := bufio.NewScanner(file)
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) > 2 {
			return nil, fmt.Errorf("%s:%d: expected token name and optional lexeme", path, lineNumber)
		}

		definition := tokenDefinition{Name: fields[0]}
		if len(fields) == 2 {
			definition.Lexeme = fields[1]
		}
		definitions = append(definitions, definition)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if len(definitions) == 0 {
		return nil, fmt.Errorf("%s: no token definitions found", path)
	}
	return definitions, nil
}

func generate(definitions []tokenDefinition) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buffer.WriteString("package lexer\n\n")
	buffer.WriteString("type TokenType int\n\n")
	buffer.WriteString("const (\n")
	for index, definition := range definitions {
		if index == 0 {
			fmt.Fprintf(&buffer, "\tToken%s TokenType = iota\n", definition.Name)
			continue
		}
		fmt.Fprintf(&buffer, "\tToken%s\n", definition.Name)
	}
	buffer.WriteString(")\n\n")

	buffer.WriteString("var StringToTokenType = map[string]TokenType{\n")
	for _, definition := range definitions {
		if definition.Lexeme == "" {
			continue
		}
		fmt.Fprintf(&buffer, "\t%q: Token%s,\n", definition.Lexeme, definition.Name)
	}
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}
